### ISSUE TITLE
Allow setting the payment recipient on the author or article level

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-publisher-wordpress#12]
e.g. https://wordpress.org/support/topic/paywall-to-dedicated-wallet/

I think we can start with the the lightning address option. Editors can add a lightning address to their profile and this then will be used to send the payment to. (instead of the global wallet setting)

Allowing people to add the other options is too much and we hope that LNURL-pay + WebLN/LNURL-verify has enough adoption and gets more adoption.

**Comment by Bobz-zg** [comment]
@bumi can you shade some light on this part of code please:
https://github.com/getAlby/lightning-publisher-wordpress/blob/master/public/class-bln-publisher-public.php#L120

What is required here is to:
1. opition `lnurl_meta_tag` should be enabled
2. if `lnurl_meta_tag_lnurlp` exists use `lnurl_meta_tag_lnurlp`, otherwise use endpoint: `/lnp-alby/v1/lnurlp`

Questions:
1. In case we add meta tag with endpoint `/lnp-alby/v1/lnurlp` SATS will go to main wallet, the one from Wallet Settings?
2. If yes, I might also want to check if wallet is connected before adding tag?

**Comment by bumi** [comment]
This is the spec for this meta tag: https://github.com/BitcoinAndLightningLayerSpecs/rfc/issues/1
basically websites can say where visitiors can send money to (donations/value4value)

yes, incase no specific lightning address/lnurp is configured the `/lnp-alby/v1/lnurlp` endpoint will use the main wallet from the wallet settings. 

but users can overwrite this default and specify a global lightning address.


But to keep things simple I would ignore this lnurl meta tag for now and only use the author's lightning address in the paywall case. 
Otherwise we would probably pass in the post id to the `lnurlp` [endpoint](https://github.com/getAlby/lightning-publisher-wordpress/blob/master/includes/rest-api/controllers/class-rest-lnurlp.php) and there also pass it on to the callback url to then be able to create an invoices with the author's details of a specific post.

**Comment by Bobz-zg** [comment]
Ok, I have pushed update to this branch: https://github.com/getAlby/lightning-publisher-wordpress
Field is added in contact methods list:
<img width="498" alt="Screenshot 2023-03-19 at 17 46 36" src="https://user-images.githubusercontent.com/420604/226171092-bf42ab4b-ec16-4d54-8422-b527b80bf03d.png">

There is also a filter, it is possible to programatically update address as well.
Comments are inline, check and let me know.

**Comment by bumi** [comment]
Great, I opened the PR to discuss on the code. 
I left some comments there. can we use the user specific ln address also for the paywall? (configuring the lightningClient based on the author)?
